module.exports = {
    "dLVerifyRequest": process.env.REACT_APP_DL_VERIFY_SUBMISSION,


    "requestSmsCode": process.env.REACT_APP_GET_SMS_CODE,
    "verifySmsCode": process.env.REACT_APP_VERIFY_SMS_CODE,


    "CV_DETECT_ID": process.env.REACT_APP_CV_DETECT_ID,
    "CV_DETECT_ID_PREDICTION_KEY": process.env.REACT_APP_CV_DETECT_ID_PREDICTION_KEY,


    "READAPI_READ": process.env.REACT_APP_READAPI_READ,
    "READAPI_KEY_NAME": process.env.REACT_APP_READAPI_KEY_NAME,
    "READAPI_KEY_VALUE": process.env.REACT_APP_READAPI_KEY_VALUE,


    "FACEAPI_DETECT": process.env.REACT_APP_FACEAPI_DETECT,
    "FACEAPI_FACEID": process.env.REACT_APP_FACEAPI_FACEID,
    "FACEAPI_VERIFY": process.env.REACT_APP_FACEAPI_VERIFY,
    "FACEAPI_KEY": process.env.REACT_APP_FACEAPI_KEY,
    "FACEAPI_KEYNAME": process.env.REACT_APP_FACEAPI_KEYNAME,


    "COSMOSDB_ENDPOINT": process.env.REACT_APP_COSMOSDB_ENDPOINT,
    "COSMOSDB_KEY": process.env.REACT_APP_COSMOSDB_KEY,
    "COSMOSDB_ID_DB": process.env.REACT_APP_COSMOSDB_ID_DB,
    "COSMOSDB_ID_CONTAINER": process.env.REACT_APP_COSMOSDB_ID_CONTAINER,

    "HASH": process.env.REACT_APP_HASH,

    "UPDATE_VERIFIEDFIELDS": process.env.REACT_APP_UPDATE_VERIFIEDFIELDS
}